# Generated by Django 5.2.7 on 2025-10-24 00:22

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Store Category',
                'verbose_name_plural': 'Store Categories',
                'db_table': 'store_categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('store_type', models.CharField(choices=[('local', 'Local Store'), ('chain', 'Chain Store'), ('restaurant', 'Restaurant'), ('grocery', 'Grocery Store'), ('supermarket', 'Supermarket')], default='local', max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='stores/logos/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='stores/covers/')),
                ('phone_number', models.CharField(max_length=17)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(default='USA', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('delivery_radius', models.DecimalField(decimal_places=2, default=5.0, help_text='Delivery radius in miles', max_digits=5)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=2.99, max_digits=10)),
                ('estimated_delivery_time', models.IntegerField(default=30, help_text='Estimated delivery time in minutes')),
                ('business_hours', models.JSONField(blank=True, default=dict, help_text='Store business hours')),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('is_open', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('total_reviews', models.IntegerField(default=0)),
                ('total_orders', models.IntegerField(default=0)),
                ('business_license', models.FileField(blank=True, null=True, upload_to='stores/documents/')),
                ('tax_id', models.CharField(blank=True, max_length=50)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_stores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
                'db_table': 'stores',
                'ordering': ['-is_featured', '-average_rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StoreCategoryMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_mappings', to='stores.storecategory')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_mappings', to='stores.store')),
            ],
            options={
                'db_table': 'store_category_mappings',
            },
        ),
        migrations.CreateModel(
            name='StoreStaff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('cashier', 'Cashier'), ('delivery', 'Delivery Personnel'), ('kitchen', 'Kitchen Staff')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('hired_date', models.DateField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='stores.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_positions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Store Staff',
                'verbose_name_plural': 'Store Staff',
                'db_table': 'store_staff',
            },
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['city', 'status'], name='stores_city_d34005_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['status', 'is_open'], name='stores_status_eb4269_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='storecategorymapping',
            unique_together={('store', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='storestaff',
            unique_together={('store', 'user')},
        ),
    ]
